include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/generated/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore

formatter:
  page_width: 120
  trailing_commas: preserve
