targets:
  $default:
    builders:
      slang_build_runner:
        options:
          base_locale: pt
          input_directory: assets/i18n
          input_file_pattern: .i18n.json
          output_directory: lib/src/shared/presentation/i18n
          output_file_name: translations.g.dart
          namespaces: false
          string_interpolation: braces
          generate_enum: false
      freezed:
        options:
          # Tells Freezed to format .freezed.dart files.
          # This can significantly slow down code-generation.
          # Disabling formatting will only work when opting into Dart 3.7 as a minimum
          # in your project SDK constraints.
          format: true
          # Disable the generation of copyWith/== for the entire project
          copy_with: false
          equal: false
